controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

saludo:
    path: /saludo
    controller: App\Controller\DefaultController::saludo

